### ISSUE TITLE
Load gcc 8 environment in CentOS 7

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/pixeltrack-standalone#15]
Should we mention something like
```bash
source scl_source enable devtoolset-8
```
to load a GCC 8 environment for CentOS 7 ?

**Comment by makortel** [comment]
Sure, if it helps. So far on CERN machines I've just taken the compiler and CUDA from CMSSW environment. But yeah, for generic CentOS 7 machines it could be useful to add.

**Comment by felicepantaleo** [comment]
I am loading gcc8 from cvmfs:
`source /cvmfs/sft.cern.ch/lcg/contrib/gcc/8.3.0/x86_64-centos7/setup.sh`

**Comment by felicepantaleo** [comment]
for building CUPLA, this gives a good environment with the correct version of Boost:
`source /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-centos7-gcc8-opt/setup.sh`

**Comment by fwyzard** [comment]
do you know if `/cvmfs/sft.cern.ch` is accessible outside CERN ?

(I would hope so, but it should be worth checking)

**Comment by felicepantaleo** [comment]
I assume it is as LHCb/NA62/FCC are using its LCG Views to set the environment for their releases, but I don't know from first hand experience

**Comment by ghugo83** [comment]
>do you know if /cvmfs/sft.cern.ch is accessible outside CERN ?

Hopefully this was found since there, otherwise: Yes, it is possible. 
I source environments from `/cvmfs/sft.cern.ch` every day on my local machine on my home wifi (and also run CMSSW & its friends locally).

I just edited once `/etc/cvmfs/default.local` and put `CVMFS_HTTP_PROXY='DIRECT'

For CMSSW runs there was some extra squid-related local install to do, and also:
edit `/etc/cvmfs/config.d/cms.cern.ch.local` and put `export CMS_LOCAL_SITE=/etc/cvmfs/CMS_SITECONF/local`

Then `sudo cvmfs_config reload`

**Comment by fwyzard** [comment]
Done in #279
