### ISSUE TITLE
`run-scan.py` prints the wrong average

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/pixeltrack-standalone#232]
It looks like `run-scan.py` prints the wrong average when running with repeated measurements:
```
$ ./run-scan.py --minThreads 16 --maxThreads 24 --eventsPerStream 1000 --repeat 4 --warmup ./cudadev
21-10-12 09:31:17 Warming up
21-10-12 09:31:28 Processed 16000 events in 9.758109e+00 seconds, throughput 1639.66 events/s.

21-10-12 09:31:28 Number of streams 16 threads 16 events 16000
21-10-12 09:31:40 Processed 16000 events in 9.794204e+00 seconds, throughput 1633.62 events/s.
21-10-12 09:31:51 Processed 16000 events in 9.430950e+00 seconds, throughput 1696.54 events/s.
21-10-12 09:32:03 Processed 16000 events in 9.997050e+00 seconds, throughput 1600.47 events/s.
21-10-12 09:32:16 Processed 16000 events in 1.160675e+01 seconds, throughput 1378.51 events/s.
21-10-12 09:32:16 Number of streams 16 threads 16, average throughput 1378.510000

...
```

`1378.51` is the throughput of the last measurement, not the average.

**Comment by makortel** [comment]
I also noticed that this would happen while doing further developments (I haven't really used the option myself) and the reason is pretty clear
https://github.com/cms-patatrack/pixeltrack-standalone/blob/31d542c64a83fdd6b312bde4477256a3334d162a/run-scan.py#L183-L196

Before fixing it (likely as part of aforementioned developments), would it be better to include each measurement of the `--repeat` in the JSON file, or the average of those? I'd quickly think the former.
